<?php
/**
 *
 * @category    payment gateway
 * @package     Tpaycom_Magento2.1
 * @author      Tpay.com
 * @copyright   (https://tpay.com)
 */

/** @var $block \tpaycom\magento2basic\Block\Payment\tpay\Redirect */

// @codingStandardsIgnoreFile
?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
<div align="center">
    <?php echo __("In order to complete the payment you will be redirected to tpay.com. Click button below if you were not redirected automatically") ?>
    <br>
    <?php echo $block->getFormHtml() ?>
    <script type="text/javascript">
        <?php // Equivalent of domReady exec ?>
        (function() {
            document.getElementById("tpaycom_magento2basic_checkout").submit();
        })();
    </script>
</div>
</body>
</html>
