<?php
/**
 *
 * @category    payment gateway
 * @package     Tpaycom_Magento2.1
 * @author      Tpay.com
 * @copyright   (https://tpay.com)
 */

/** @var $block \tpaycom\magento2basic\Block\Payment\tpay\Redirect\Form */

// @codingStandardsIgnoreFile
?>
<form action="<?php echo $block->getAction() ?>" method="post" id="tpaycom_magento2basic_checkout" name="tpaycom_magento2basic_checkout">
    <?php foreach ($block->getTpayData() as $field => $value) : ?>
        <input type="hidden" name="<?php echo $block->escapeHtml($field) ?>" id="<?php echo $block->escapeHtml($field) ?>" value="<?php echo $block->escapeHtml($value) ?>">
    <?php endforeach; ?>
    <?php foreach ($block->getAdditionalInformation() as $field => $value) : ?>
        <input type="hidden" name="<?php echo $block->escapeHtml($field) ?>" id="<?php echo $block->escapeHtml($field) ?>" value="<?php echo $block->escapeHtml($value) ?>">
    <?php endforeach; ?>
    <input type="submit" value="<?php echo __('Redirect me to tpay.com.') ?>" id="submit_btn" name="redirect" align="center">
</form>
