name: Pull request

on:
  pull_request:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v4
        id: plugin-upload
        with:
          name: 'tpay-magento2-basic'
          path: './'

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Tpay Magento2 plugin - ${{ steps.plugin-upload.outputs.artifact-url }}'
            })
